const MAX_NUMBER_FILE: number = 1,
	DEFAULT_EXTENSIONS_IMG: string[] = ['jpeg', 'jpg', 'png'],
	DEFAULT_COLLECTION = '',
	DEFAULT_NAME_IMAGE = '',
	DEFAULT_PATH = '';

export {
	MAX_NUMBER_FILE,
	DEFAULT_EXTENSIONS_IMG,
	DEFAULT_COLLECTION,
	DEFAULT_PATH,
	DEFAULT_NAME_IMAGE,
};
